"""add thread summaries

Revision ID: e836155c0355
Revises: fedbd88e37a9
Create Date: 2026-05-16 14:22:45.551153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e836155c0355'
down_revision: Union[str, Sequence[str], None] = 'fedbd88e37a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('threads', 'gmail_thread_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('threads', 'summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('threads', 'created_at')
    op.drop_column('threads', 'priority_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('priority_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('threads', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('threads', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('threads', 'gmail_thread_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
